import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Footwear Guardian.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.hero__cover}>
        <h1 className={styles.heading}>Footwear Guardian.</h1>
        <center>
          <button className={styles.button}>
            <Link href="/reserve" className={styles.link}>
              reserve a locker
            </Link>
          </button>
        </center>
      </div>
    </>
  );
}
